name: Cloud Functions Deploy
on: [push]

jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/871023067494/locations/global/workloadIdentityPools/gcf-deploy-pool/providers/gcf-deploy-provider'
        service_account: 'gcf-deploy@persistent-370411.iam.gserviceaccount.com'


    - id: 'deploy-using-api'
      name: 部署到 Google Cloud Functions
      run: >-
        gcloud functions deploy "line-bot-using-api"
        --allow-unauthenticated
        --entry-point=callback
        --env-vars-file=.env
        --gen2
        --max-instances=1
        --memory=128Mi
        --no-user-output-enabled
        --region=us-central1
        --runtime=pyhton310
        --timeout=60s
        --trigger-http


