name: Cloud Functions Deploy
on: [push]

jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/871023067494/locations/global/workloadIdentityPools/gcf-deploy-pool/providers/gcf-deploy-provider'
        service_account: 'gcf-deploy@persistent-370411.iam.gserviceaccount.com'


    - id: 'deploy-using-api'
      name: 部署到 Google Cloud Functions
      run: >-
        gcloud functions deploy "line-bot-using-api"
        --allow-unauthenticated
        --entry-point=callback
        --gen2
        --max-instances=1
        --memory=128Mi
        --no-user-output-enabled
        --region=us-central1
        --runtime=python310
        --timeout=60s
        --trigger-http

    - name: Retrieve version
      id: 'get-url'
      run: |
        echo "URL=$(gcloud functions describe line-bot-using-api --gen2 --region=us-central1 --format="value(serviceConfig.uri)")"


    # Example of using the output
    - id: 'test'
      run: "curl -X POST \
            -H 'Authorization: Bearer ${{ secrets.CHANNEL_ACCESS_TOKEN }} ' \
            -H 'Content-Type:application/json' \
            -d '{"endpoint":""${{ steps.get-url.outputs.URL }}"}' \
            https://api.line.me/v2/bot/channel/webhook/test"




